import unittest


def alternatingCharacters(s):
    count = 0
    for i in range(1, len(s)):
        if s[i - 1] == s[i]:
            count += 1
    return count


class TestAlternatingCharacters(unittest.TestCase):
    def test_alternating_characters(self):
        self.assertEqual(alternatingCharacters("AAAA"), 3)  # ลบ 3 ตัว เหลือ "A"
        self.assertEqual(alternatingCharacters("BBBBB"), 4)  # ลบ 4 ตัว เหลือ "B"
        self.assertEqual(alternatingCharacters("ABABABAB"), 0)  # ไม่ต้องลบ
        self.assertEqual(alternatingCharacters("BABABA"), 0)  # ไม่ต้องลบ
        self.assertEqual(alternatingCharacters("AAABBB"), 4)  # ลบ 4 ตัว เหลือ "AB"
        self.assertEqual(alternatingCharacters("AABBAABB"), 4)  # ลบ 4 ตัว เหลือ "ABAB"
        self.assertEqual(alternatingCharacters("ABABABAA"), 1)  # ลบ 1 ตัว เหลือ "ABABABA"
        self.assertEqual(alternatingCharacters("ABBABBAA"), 3)  # ลบ 3 ตัว เหลือ "ABABABA"

        self.assertEqual(
            alternatingCharacters(
                "BABABBBBBABBABBBAAABBBBBBBBABBBBBABBBAABBBBABBBBBBBAABABBBBBBABBABBBBBBBBBABBBBBABBABBBBABABBBBBBBBBBBBBBBBBBBABBBBBAABABBBBBBBBBBBABABBBABBBABBBBBBBBBBABBBBBABBBABBBABBABBBBBBAABBBABABBBAABABAABBBBAABBBBBBBBBAAABBABABBABBBABBBBABBBBBABABBBBABABBBAABBABBAABBBBBBABBABBBBBBBBBBBBBBBBBABBBBBBABBBBBBBBABBABBBBBBBBBAAABBBBBBBBBABBABABBBAAABBBBBBABBABBBBBBBABBBBBABBBABBAABAABAAABABBBBBBBABBBBABBBBBABBBBBBABBABBBBBBBBBBBBBBBBBABBABBBAABBBBBAABABBBBBBAABBBBBBBBBABBBBBABBABBBBBBBBBABBBBBBABBBABBBBBABBBBBBBBBBBBBBBBBBABBBBBBBBBBABBBBABABBBBBBBBABBBBBBBBBABBBBBAAABBBBABABABBBBABBBBBBBBBBAABBBBBBBBABBAABBBBBBBBBABAABBBBBBBBBBBBABBBBABABBBBBBBBABBBBBBBBBBBBABBBBABBBBBABBBBBBBBBBABBAABBBABBBBBBBBBABBBBAABBBBBBBBABABABBBBBABBBBBBBBBBBBBBBBBBABBBBABBBBBABBABABAABBBABBBBBBBBBAABABABBBBBBBBAABBBBABBABBBABBBBAABBABABBBBABAABBBBBBBBBBABBABBBBBABAABBBBBBBBBBBBABABBBBBBBBBBABAABABBBBABBBBBBBBBBBBBABBBBBABBABBAABBBBABBBBBBBBBBBAABBBBBBBBBBBBBBAABABBBBBABBBBBBBBBABBBBABBBBABABBABBBBABABBBABABAAABBBBAAAAAABBBA"
            ),
            660,
        )  # test 4 in hackerrank
